update_search_password= "123456"

["gcp_service_account_firestore"]
type = "service_account"
project_id = "busca-ciap2"
private_key_id = "b1a84ce9cd8bf7b427801fbdde5b70a49c5f97ee"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDY/5bo/L0o3jL0\nCWqM7HA0UHca8r0GqsowUmZnS1susOqiNsl3kMTFQEdkFf8exBVDWqtekC3Et3A3\nVeR8aUzepnlyMAk2cR5stM504spBL28B6eMQ67HFJDLBV7kDPNShYaOSagQ6ZTb6\nFNM5FoAz7084ntEFzQgqqg8JkXa7KjpNeY0p1xzih9ALMlC9xud2tTD2XC14+A2s\nx/MWdZ0dlC+ADO7wJEEqN+Z1toFDmNO38HWCWh22ypSOLW0SKLq2uYeAdjUzoL31\nR+V+47R1ILFW7CQtmJRyJW8Rab/vUhvhU4HyuqaRUN92/uYRiH5pyq08mA7yZ72U\nH0q+I5EXAgMBAAECggEARz6bQIGCZYGWfxL8XapfKH3mrP1XXHIEkhrrrixKkqjZ\nUErmmI/6WrzA87ZZHbPJO2TwcMqrjDOh7zkPHF3CNDO6Geh1jd9T2uL+CdhQCVjW\nfG1a9Lo9knlRBLOVdd+p/BY/ixmtq7KBe1gNBWhCzUpb2z4haGMptEBDUaPltIsM\nnfVAkNBYaPo+/zCan4EI606zwgnKIJGXQt0hv/aD2edIT0lQKEFqN8r0sxBoQLdM\nOp9cvBhVz4outZW+1wwStggUyO3Kq2XY9jyPPojGTxUBC2gYb/sm2l0rMUNWGedO\nGyndFM843zVS103ZUDLbFvPQXGQ2+xinBlCL5NmRwQKBgQD8BIwwduyTnrV3kGls\nmQv1wsLx3ZLC+dRoXDMHRDWdfi4LKII8GzeqLgyBwNMNQHOcVPSOpE1LVitcv+vh\nb83j+GNoJZ9KHNGJYSo6P++dGc3Y7amnGSYLA1VEpBegiFOgmAbSi812TeTR8TIQ\nAOlF7RkTZpR5pC4MLzWYb9jVNwKBgQDcbWIGACHnofKKbq2BVTeHzG+cQgRqASvP\nPISK9kjaP1YgE2u5Ui/XUxpcswTw6VhLE/0uuSem5K9fNpSV3lr18AwDw6Z23Ad9\nDrzphES8HbDDZSpQiNKKUaz9adQZajy9z9yGHAcX5FuxbZGIBziKjAHPg/AODOBa\nR9QTfgsTIQKBgQD223GCq4ry0nxIgNFzibq4Ya1ZA0QV7mfMTbvCO2MVQRrS3Tws\nqjBtZyvjEUDqcx6LnH/tFS2NRPu2n1vrd/vCeXTN+EQ+cVoiamXVpvkL9tG20p3i\nyvSDxyEH2oA2RDM+VIwiQsTgRE6GAu+Z03qsfyGX6lw3hsWAM+IYzj4kIwKBgAsP\nEdPrPcg5P8niM6JBfD+76f2U8lO/K0uCZcPzB0Sr2M5TKxxpGy1aZgAwmxbbHirm\nHdWyRGMDJilIu7upJDcii/fEYR2lfFqx2ph8olYtxyiGctEHjEiUQHGWVaXQxqtf\nOlkgHtr8Af2s2ZhRhGyvCYg3vlt2Gettnx47PKMBAoGAf1zynwO/o/TM3S2T1vMd\nO9mScG8ol6WrGvAlKDr8RItKPQsMTi2mGMT3frhJzgMIGiRlRyLsMLksJM30LHsZ\nYXoXdmQOHZJuYiTg729H5fMoYYPg5OtyQJCO9Oe3xR9SRUq6v47jud1/uTbed24N\nfPnjBXKpuklBANj7HtxW24w=\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-egj8b@busca-ciap2.iam.gserviceaccount.com"
client_id = "105202881649691110347"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-egj8b%40busca-ciap2.iam.gserviceaccount.com"

["gcp_service_account"]
apiKey = "AIzaSyDQEdIQuH691Blhp1lDca-_0fWyJMza0K8"
authDomain = "busca-ciap2.firebaseapp.com"
projectId = "busca-ciap2"
storageBucket = "busca-ciap2.appspot.com"
messagingSenderId = "774609266727"
appId = "1:774609266727:web:f46a5dabc7bcf710f8c602"
measurementId = "G-QPE6FM97NY"

["openai"]
key = "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"